apiVersion: v2
name: common
description: Nected common helm chart

home: https://nected.ai/

keywords:
  - Nected
  - Workflow automation
  - BRE, Business Rule Engine
  - Decision management platform
  - No-Code / Low-Code Rule Engine
  - No-Code / Low-Code Workflow automation

maintainers:
  - name: Socioverse Tech Private Ltd.
    url: https://nected.ai/

sources:
  - https://charts.nected.io

appVersion: "0.1.6"
type: application
version: 0.1.6

dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
    - bitnami-common
    version: 2.x.x
    alias: external
