apiVersion: v2
name: konark
description: Konark, Nected fronend application

home: https://nected.ai/

keywords:
  - Nected
  - Workflow automation
  - BRE, Business Rule Engine
  - Decision management platform
  - No-Code / Low-Code Rule Engine
  - No-Code / Low-Code Workflow automation

maintainers:
  - name: Socioverse Tech Private Ltd.
    url: https://nected.ai/

sources:
  - https://charts.nected.io

appVersion: "op0.13.4"
type: application
version: 0.4.6

dependencies:
- name: common
  repository: https://charts.nected.io/
  tags:
  - nected-common
  version: 0.x.x
