apiVersion: v2
name: azurecert
description: Nected azurecert helm chart

home: https://nected.ai/

keywords:
  - Nected
  - Workflow automation
  - BRE, Business Rule Engine
  - Decision management platform
  - No-Code / Low-Code Rule Engine
  - No-Code / Low-Code Workflow automation

maintainers:
  - name: Socioverse Tech Private Ltd.
    url: https://nected.ai/

sources:
  - https://charts.nected.io

appVersion: "0.1.3"
type: application
version: 0.1.3
