{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "common.serviceAccountName" . }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "common.serviceAccountName" . }}-role
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "create"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "common.serviceAccountName" . }}-binding
subjects:
- kind: ServiceAccount
  name: {{ include "common.serviceAccountName" . }}
roleRef:
  kind: Role
  name: {{ include "common.serviceAccountName" . }}-role
  apiGroup: rbac.authorization.k8s.io
{{- end }}